/**
 * @fileoverview warnings reported by the parser
 * @author Bhsd
 */
'use strict';

// ------------------------------------------------------------------------------
// This rule reports all warnings generated by the upstream parser,
// [wikiparser-node](https://github.com/bhsd-harry/wikiparser-node)
// ------------------------------------------------------------------------------

/** @type {import('eslint').Rule.RuleModule} */
module.exports = {
	meta: {
		type: 'suggestion',
		docs: {
			description: 'warnings reported by the parser',
			recommended: false,
			url: null, // URL to the documentation page for this rule
		},
		fixable: null, // Or `code` or `whitespace`
		schema: [],
	},
	create(context) {
		/** @type {{parserServices: {errors: import('wikilint').AstText.LintError[]}}} */
		const {parserServices: {errors}} = context;
		return {
			Program() {
				for (const {severity, message, startLine, startCol, endLine, endCol} of errors) {
					if (severity === 'warning') {
						context.report({
							message,
							loc: {
								start: {line: startLine + 1, column: startCol},
								end: {line: endLine + 1, column: endCol},
							},
						});
					}
				}
			},
		};
	},
};
